import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import type { Guild } from "../../../../packages/shared/src/types/guild.type";
import type { Item } from "../../../../packages/shared/src/types/item.type";
import {
    ItemName,
    ItemRarity,
    ItemType,
    ItemStatus,
} from "../../../../packages/shared/src/types/item.type";
import { AdventurerType } from "../../../../packages/shared/src/types/adventurer.type";

const mockGuildApi: Guild = {
    id: "guild-1",
    name: "La Guilde des Héros",
    bank: {
        balance: 15750,
        transactions: [
            {
                id: "t1",
                name: "Récompense - Retrieve the Azure Gem",
                amount: 150,
                date: new Date("2026-01-16T10:30:00Z").getTime(),
            },
            {
                id: "t2",
                name: "Vente d'équipement usagé",
                amount: 85,
                date: new Date("2026-01-18T14:20:00Z").getTime(),
            },
            {
                id: "t3",
                name: "Achat de potions de soin (x10)",
                amount: -500,
                date: new Date("2026-01-20T09:15:00Z").getTime(),
            },
            {
                id: "t4",
                name: "Réparation d'équipement",
                amount: -120,
                date: new Date("2026-01-22T16:45:00Z").getTime(),
            },
            {
                id: "t5",
                name: "Contribution d'un bienfaiteur",
                amount: 1000,
                date: new Date("2026-01-25T11:00:00Z").getTime(),
            },
            {
                id: "t6",
                name: "Achat d'armure épique",
                amount: -780,
                date: new Date("2026-01-27T13:30:00Z").getTime(),
            },
            {
                id: "t7",
                name: "Taxe mensuelle de la guilde",
                amount: -200,
                date: new Date("2026-01-31T23:59:00Z").getTime(),
            },
            {
                id: "t8",
                name: "Vente d'items rares au marché",
                amount: 450,
                date: new Date("2026-02-01T08:15:00Z").getTime(),
            },
        ],
    },
    adventurers: [],
    inventory: [
        // Items disponibles dans la guilde
        {
            id: "gi1",
            name: ItemName.SWORD,
            description: "Une épée de qualité standard pour débutants.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 120,
            type: ItemType.WEAPON,
            rarity: ItemRarity.COMMON,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi2",
            name: ItemName.HEALING_POTION,
            description: "Potion de soin basique.",
            quantity: 10,
            isConsumable: true,
            price: 50,
            type: ItemType.POTION,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi3",
            name: ItemName.SHIELD,
            description: "Un bouclier en acier robuste.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 180,
            type: ItemType.ARMOR,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi4",
            name: ItemName.BOW,
            description: "Arc composite de chasseur.",
            durability: 88,
            maxDurability: 100,
            isConsumable: false,
            price: 220,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.ARCHER, AdventurerType.ROGUE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi5",
            name: ItemName.ARROW,
            description: "Carquois de 20 flèches.",
            quantity: 50,
            isConsumable: true,
            price: 30,
            type: ItemType.WEAPON,
            rarity: ItemRarity.COMMON,
            profiles: [AdventurerType.ARCHER],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi6",
            name: ItemName.STAFF,
            description: "Bâton de mage enchanté.",
            durability: 92,
            maxDurability: 100,
            isConsumable: false,
            price: 380,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.ENCHANTER, AdventurerType.ARCANE_MAGE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi7",
            name: ItemName.HELMET,
            description: "Casque de protection renforcé.",
            durability: 90,
            maxDurability: 100,
            isConsumable: false,
            price: 150,
            type: ItemType.ARMOR,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi8",
            name: ItemName.MAGIC_RING,
            description: "Anneau magique amplifiant les sorts.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 950,
            type: ItemType.MISC,
            rarity: ItemRarity.EPIC,
            profiles: [AdventurerType.ENCHANTER, AdventurerType.ARCANE_MAGE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi9",
            name: ItemName.AXE,
            description: "Hache de combat lourde.",
            durability: 85,
            maxDurability: 100,
            isConsumable: false,
            price: 290,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.BARBARIAN, AdventurerType.WARRIOR],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi10",
            name: ItemName.HEALING_POTION,
            description: "Potion de soin supérieure.",
            quantity: 7,
            isConsumable: true,
            price: 80,
            type: ItemType.POTION,
            rarity: ItemRarity.UNCOMMON,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi11",
            name: ItemName.ARMOR,
            description: "Armure complète en mithril.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 650,
            type: ItemType.ARMOR,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi12",
            name: ItemName.DAGGER,
            description: "Dague d'assassin empoisonnée.",
            durability: 78,
            maxDurability: 100,
            isConsumable: false,
            price: 320,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.ROGUE],
            status: ItemStatus.AVAILABLE,
        },
        // Items supplémentaires disponibles
        {
            id: "gi13",
            name: ItemName.SWORD,
            description: "Épée en acier forgée avec soin.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 150,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi14",
            name: ItemName.BOW,
            description: "Arc long de qualité supérieure.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 320,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.ARCHER, AdventurerType.ROGUE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi15",
            name: ItemName.ARROW,
            description: "Flèches en acier trempé.",
            quantity: 30,
            isConsumable: true,
            price: 40,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.ARCHER],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi16",
            name: ItemName.HEALING_POTION,
            description: "Potion de soin de qualité moyenne.",
            quantity: 15,
            isConsumable: true,
            price: 60,
            type: ItemType.POTION,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi17",
            name: ItemName.STAFF,
            description: "Bâton d'érudition avec gemmes mineures.",
            durability: 88,
            maxDurability: 100,
            isConsumable: false,
            price: 420,
            type: ItemType.WEAPON,
            rarity: ItemRarity.EPIC,
            profiles: [AdventurerType.ENCHANTER, AdventurerType.ARCANE_MAGE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi18",
            name: ItemName.SHIELD,
            description: "Bouclier de tour renforcé.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 240,
            type: ItemType.ARMOR,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi19",
            name: ItemName.HELMET,
            description: "Heaume en fer lourd.",
            durability: 85,
            maxDurability: 100,
            isConsumable: false,
            price: 180,
            type: ItemType.ARMOR,
            rarity: ItemRarity.UNCOMMON,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi20",
            name: ItemName.ARMOR,
            description: "Plastron de combat en cuir renforcé.",
            durability: 80,
            maxDurability: 100,
            isConsumable: false,
            price: 380,
            type: ItemType.ARMOR,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.ROGUE, AdventurerType.ARCHER],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi21",
            name: ItemName.DAGGER,
            description: "Dague de jet équilibrée.",
            durability: 92,
            maxDurability: 100,
            isConsumable: false,
            price: 280,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.ROGUE],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi22",
            name: ItemName.AXE,
            description: "Hache à deux mains dévastatrice.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 480,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.BARBARIAN, AdventurerType.WARRIOR],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi23",
            name: ItemName.MAGIC_RING,
            description: "Anneau de protection mineure.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 650,
            type: ItemType.MISC,
            rarity: ItemRarity.RARE,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi24",
            name: ItemName.SWORD,
            description: "Épée longue élégante.",
            durability: 90,
            maxDurability: 100,
            isConsumable: false,
            price: 180,
            type: ItemType.WEAPON,
            rarity: ItemRarity.COMMON,
            profiles: [AdventurerType.WARRIOR, AdventurerType.PALADIN],
            status: ItemStatus.AVAILABLE,
        },
        {
            id: "gi25",
            name: ItemName.HEALING_POTION,
            description: "Grand flacon de soin.",
            quantity: 5,
            isConsumable: true,
            price: 120,
            type: ItemType.POTION,
            rarity: ItemRarity.RARE,
            profiles: [],
            status: ItemStatus.AVAILABLE,
        },
        // Les items du mock original (déjà utilisés dans quests) - référencés dans la guilde
        {
            id: "301",
            name: ItemName.STAFF,
            description: "An enchanted staff infused with arcane energy.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 450,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.ENCHANTER, AdventurerType.ARCANE_MAGE],
            status: ItemStatus.IN_USE,
            questId: "1",
        },
        {
            id: "302",
            name: ItemName.ARMOR,
            description: "Epic protective robes woven with magic resistance.",
            durability: 88,
            maxDurability: 100,
            isConsumable: false,
            price: 780,
            type: ItemType.ARMOR,
            rarity: ItemRarity.EPIC,
            profiles: [AdventurerType.ENCHANTER],
            status: ItemStatus.IN_USE,
            questId: "1",
        },
        {
            id: "303",
            name: ItemName.DAGGER,
            description: "A poisoned dagger perfect for stealth attacks.",
            durability: 78,
            maxDurability: 100,
            isConsumable: false,
            price: 280,
            type: ItemType.WEAPON,
            rarity: ItemRarity.RARE,
            profiles: [AdventurerType.ROGUE],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "304",
            name: ItemName.HEALING_POTION,
            description: "A potent healing elixir.",
            quantity: 3,
            isConsumable: true,
            price: 50,
            type: ItemType.POTION,
            rarity: ItemRarity.UNCOMMON,
            profiles: [],
            status: ItemStatus.IN_USE,
            questId: "1",
        },
        {
            id: "305",
            name: ItemName.MAGIC_RING,
            description: "A legendary ring that amplifies magical abilities.",
            durability: 100,
            maxDurability: 100,
            isConsumable: false,
            price: 1200,
            type: ItemType.MISC,
            rarity: ItemRarity.LEGENDARY,
            profiles: [AdventurerType.ENCHANTER, AdventurerType.ARCANE_MAGE],
            status: ItemStatus.IN_USE,
            questId: "1",
        },
        {
            id: "306",
            name: ItemName.HELMET,
            description: "A mystical helmet with protective enchantments.",
            durability: 92,
            maxDurability: 100,
            isConsumable: false,
            price: 320,
            type: ItemType.ARMOR,
            rarity: ItemRarity.RARE,
            profiles: [],
            status: ItemStatus.IN_USE,
            questId: "1",
        },
        {
            id: "307",
            name: ItemName.BOW,
            description: "A silent crossbow for ranged precision.",
            durability: 85,
            maxDurability: 100,
            isConsumable: false,
            price: 340,
            type: ItemType.WEAPON,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.ROGUE, AdventurerType.ARCHER],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "308",
            name: ItemName.HEALING_POTION,
            description: "Emergency healing potion.",
            quantity: 2,
            isConsumable: true,
            price: 50,
            type: ItemType.POTION,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "309",
            name: ItemName.AXE,
            description: "A massive battle axe forged for destruction.",
            durability: 92,
            maxDurability: 100,
            isConsumable: false,
            price: 420,
            type: ItemType.WEAPON,
            rarity: ItemRarity.EPIC,
            profiles: [AdventurerType.BARBARIAN, AdventurerType.WARRIOR],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "310",
            name: ItemName.SHIELD,
            description: "A reinforced shield for heavy combat.",
            durability: 88,
            maxDurability: 100,
            isConsumable: false,
            price: 250,
            type: ItemType.ARMOR,
            rarity: ItemRarity.UNCOMMON,
            profiles: [AdventurerType.BARBARIAN, AdventurerType.PALADIN],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "311",
            name: ItemName.HEALING_POTION,
            description: "A restorative potion for battle wounds.",
            quantity: 5,
            isConsumable: true,
            price: 50,
            type: ItemType.POTION,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
        {
            id: "312",
            name: ItemName.HELMET,
            description: "A sturdy iron helmet for protection.",
            durability: 95,
            maxDurability: 100,
            isConsumable: false,
            price: 180,
            type: ItemType.ARMOR,
            rarity: ItemRarity.COMMON,
            profiles: [],
            status: ItemStatus.IN_USE,
            questId: "2",
        },
    ],
};

export function useGuild() {
    const fetchGuild = async (): Promise<Guild> => {
        return mockGuildApi;
    };
    const getGuild = useQuery({
        queryKey: ["guild"],
        queryFn: fetchGuild,
    });
    return getGuild;
}

export function useAddItem() {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: (newItem: Item) => {
            if (mockGuildApi.inventory) {
                mockGuildApi.inventory.push(newItem);
            }
            return Promise.resolve();
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["guild"] });
        },
    });
}

export function useUpdateItem() {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: (updatedItem: Item) => {
            if (mockGuildApi.inventory) {
                const index = mockGuildApi.inventory.findIndex(
                    (item) => item.id === updatedItem.id,
                );
                if (index !== -1) {
                    mockGuildApi.inventory[index] = updatedItem;
                }
            }
            return Promise.resolve();
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["guild"] });
        },
    });
}

export { mockGuildApi };
